### PR TITLE
Add github action validating instances.json

### PR DESCRIPTION
**Pull request by Wint3rmute**
Hey,

While browsing the "add new instance" PRs in this repository, I noticed that many people make mistakes while editing `instances.json` (including me, at #189). 

I thought that it would be a good idea to automate the process of validating `instances.json` with a GitHub action. Probably will save this repo's maintainers some time :)

### CODE REVIEW

**Comment by juniorbotelho** [comment]
Great idea, if your PR is accepted, I propose to help maintain these settings.

**Comment by mad-reyk** [comment]
I don't think it's a good idea to lock free as in freedom software on
proprietary and totally anti-privacy repository vendor, that also
cannot be browsed correctly and safe (that is without JavaScript or
any other client-side scripts, so GitLab is totally unacceptable)

**Comment by juniorbotelho** [comment]
> I don't think it's a good idea to lock free as in freedom software on proprietary and totally anti-privacy repository vendor, that also cannot be browsed correctly and safe (that is without JavaScript or any other client-side scripts, so GitLab is totally unacceptable)

Okay, you have a good point of view, but don't forget that tools don't belong to the final code. These tools are just ways to decrease errors. The core of LibreX remains free, and the AGPL license is still in effect.

This means that the code can be modified and used by end-users as they see fit. If a user wishes to remove the 'Docker' and 'GitHub Action' tools, they have the freedom to do so.

**Comment by Wint3rmute** [comment]
@mad-reyk following your line of thought, just using GitHub for hosting is a bad idea. Imo if there's a free tool you can use to help the project growth, there's no reason not to use it. 

The check I'm suggesting to add is in no way critical for the project. The CI pipeline itself (outside of the Github Acitons environment) uses only FOSS software - Ubuntu, `bash` and `jq`, it won't be a problem to migrate it to a more open CI/CD system in the future, if such a system comes around. I can suggest [Drone CI](https://www.drone.io) as such a system :)

**Pull request closed without merging**
