### PR TITLE
improved the overall user interface, making it cleaner and more compact.

### PR DESCRIPTION
**Pull request by Extravi**
screenshot: https://i.ibb.co/Pgk3Zr8/Screenshot-20220814-045738.png

### CODE REVIEW

**Comment by wael444** [comment]
wael approved

**Review by wael444 — APPROVED** [review]

**Review by PetrifiedOak — APPROVED** [review]
oak approved

**Comment by TeknosQuet** [comment]
based improvement, teknos approve

**Review by TeknosQuet — APPROVED** [review]
based improvement, teknos approve

**Comment by z-ffqq** [comment]
ffqq approve

**Review by z-ffqq — APPROVED** [review]
good changes

**Comment by AVeryNormalGuy** [comment]
bongo approve

**Review by AVeryNormalGuy — APPROVED** [review]
bongo approve

**Comment by Extravi** [comment]
removed bold font for search menu and made icons smaller

**Comment by Extravi** [comment]
better mobile view

**Comment by Extravi** [comment]
screenshot of mobile view: https://i.ibb.co/3hJ8xyY/Screenshot-20220814-214428.png

**Comment by Extravi** [comment]
made mobile logo clickable and change color to match user theme

**Comment by Extravi** [comment]
made some edits to border radius and dark theme

**Comment by Extravi** [comment]
more updates to mobile ui https://i.ibb.co/K0gXdqr/Screenshot-20220815-002155.png 

special-result-container is now separate from text-result-container

**Comment by Extravi** [comment]
done both mobile and desktop edits

desktop: https://i.ibb.co/4tVBrqM/Screenshot-20220815-005930.png
mobile: https://i.ibb.co/cF4Z7M7/Screenshot-20220815-010004.png

**Comment by Extravi** [comment]
@hnhx ready to merge :+1:

**Comment by Extravi** [comment]
@rubynt i already made a pull request to fix the user interface  

screenshots
desktop: https://i.ibb.co/4tVBrqM/Screenshot-20220815-005930.png
mobile: https://i.ibb.co/sKpt5tq/Screenshot-20220815-051522.png

**Comment by Extravi** [comment]
removed custom fonts

**Comment by Extravi** [comment]
@hnhx removed all custom icons ready for merge

**Pull request merged**
