### PR TITLE
Added new instance: librex.myroware.eu

### PR DESCRIPTION
**Pull request by MyRoWARE**

### CODE REVIEW

**Comment by hnhx** [comment]
Hey! It seems like librex.myroware.eu (212.227.31.10) is in Germany. Could you fix the country location?

**Comment by MyRoWARE** [comment]
Oh yea you're right. I forgot that this server is located in Germany. Going to fix it now.

**Comment by hnhx** [comment]
Json is not correct now, because of the "," in the end :x

**Comment by MyRoWARE** [comment]
Oh yea forgot to remove it. It is now removed. Im so sorry.

**Comment by hnhx** [comment]
There is a plus enter now for no reason XD

**Comment by MyRoWARE** [comment]
I removed that enter xDDDD

**Pull request merged**
