### PR TITLE
Add librex.baczek.me instance

### PR DESCRIPTION
**Pull request by Wint3rmute**
Hey!

Please consider adding my [Librex instance](https://librex.baczek.me) to the official list of instances :)

*Note:* google sometimes blocks my IP since I'm already hosting a [public searx instance](searx.space/).

### CODE REVIEW

**Comment by hnhx** [comment]
Hey! The format of the JSON is incorrect, could you fix that?

**Comment by Wint3rmute** [comment]
Oh my bad! It's fixed now!

**Comment by hnhx** [comment]
Also it seems like your video results are broken, could you fix that as well?

**Comment by Wint3rmute** [comment]
`https://` was missing in my configuration. It's working now, [take a look](https://librex.baczek.me/search.php?q=chad+librebooted+thinkpad&t=2&p=0)

**Pull request merged**
