### PR TITLE
Center results

### PR DESCRIPTION
**Pull request by rubynt**

### CODE REVIEW

**Comment by Extravi** [comment]
want you want to do it broken 
https://i.ibb.co/B6JSYGC/Screenshot-20220815-185212.png
https://i.ibb.co/tCJzKwx/Screenshot-20220815-185228.png

and i already fixed the design https://github.com/hnhx/librex/pull/41

**Comment by rubynt** [comment]
Please stop posting meaningless comments. You didnt do what i wanted to do here.
If you would ask it depends on my other PR.

**Comment by Extravi** [comment]
the "Fetched the results in ... seconds" is very small and the border is off.  It's not meaningless you must be trolling.

**Comment by hnhx** [comment]
I'm sorry but this doesn't look good

**Pull request closed without merging**
