### PR TITLE
Design fix

### PR DESCRIPTION
**Pull request by rubynt**

### CODE REVIEW

**Comment by Extravi** [comment]
i did that already: https://github.com/hnhx/librex/pull/41

desktop: https://i.ibb.co/4tVBrqM/Screenshot-20220815-005930.png
mobile: https://i.ibb.co/cF4Z7M7/Screenshot-20220815-010004.png

**Comment by rubynt** [comment]
I think yours fit in the theme option while i try to fix some ui design. I dont have any problem with the colors and icons. I think mines look more tighter. 
Let the maintainer choose which options would fit the best :^)

**Comment by Extravi** [comment]
> I think yours fit in the theme option while i try to fix some ui design. I dont have any problem with the colors and icons. I think mines look more tighter. I think let the maintainer choose which options would fit the best :^)

I reduced the size of the user interface, which goes beyond themes. Take a look at the screenshots below:

Desktop: https://i.ibb.co/4tVBrqM/Screenshot-20220815-005930.png
Mobile: https://i.ibb.co/sKpt5tq/Screenshot-20220815-051522.png

**Comment by rubynt** [comment]
Can you please stop spamming everything with your images and repeating the same sentence? Our patches doesnt even look the same(without your theming and icons).
Stop pushing people off and let the maintainers choose which fits the project better :^).

**Pull request closed without merging**
