### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sarthac**
add instance https://search.sarthak.click

### CODE REVIEW

**Comment by codedipper** [comment]
Add your instance to `instances.json`.

**Comment by osarthak** [comment]
I already did, and pull request

**Comment by hnhx** [comment]
Your site connects to multiple domains and contains a custom font, once you remove these I will add your instance.

**Comment by Sarthac** [comment]
removed costume font,icons. using default 'Arial' font. Now site doesn't connect with multiple domains

**Pull request closed without merging**
