### PR TITLE
Move special results to right and fix button resizing on hover.

### PR DESCRIPTION
**Pull request by amogusussy**
When you seach and there's a special result from wikipedia, it blocks half the page, to where there's only search results, I've fixed it by moving it to the right of the search results.
On the index.php page (and settings), when you hover over the buttons, it moves the other button to the side a bit.

### CODE REVIEW

**Comment by hnhx** [comment]
could you share a screenshot of how it looks like?

**Comment by amogusussy** [comment]
[This is what it looks like in full screen.](https://i.imgur.com/rzLi0fG.png)
It goes out of frame when the resolution is <960px so I've made it go back to normal when the resolution is under. https://i.imgur.com/kUXXLTh.png

**Comment by amogusussy** [comment]
> could you share a screenshot of how it looks like?

Here's an interactive version too.
https://surcharge2967.neocities.org/gentoo%20-%20LibreX.html

**Comment by Extravi** [comment]
you need to clear your browser cache and refresh that's all

**Comment by Extravi** [comment]
It does not work correctly on mobile. 
https://i.ibb.co/F3X92k9/Screenshot-20220816-184702.png

**Review by Extravi — CHANGES_REQUESTED** [review]
add ```margin-right: 0px;``` to 
```
@media only screen and (max-width: 960px) {
    .special-result-container {
        position: relative;
        float: none;
        margin-left: 116px;
        width: 500px;
        margin-right: 0px;
    }
}
```

**Comment by Extravi** [comment]
screenshot of changes https://i.ibb.co/ZdnztgW/Screenshot-20220816-185444.png

**Comment by Extravi** [comment]
@amogusussy https://github.com/amogusussy/librex/pull/1 fixed for mobile support screenshot above ^^

**Comment by Extravi** [comment]
you can test it here: https://librex.extravi.dev/search.php?q=ubuntu&p=0&type=0 

I updated my instance to it

**Comment by Extravi** [comment]
I think moving it to the right more might look better.

**Pull request closed without merging**
