### PR TITLE
Add librex.weryi.xyz

### PR DESCRIPTION
**Pull request by amogusussy**
I've made a few UI changes on this instance.
If you want to view the changes, there's a tar.gz file [here](librex.weryi.xyz/librex.tar.gz) that you can compare with something like diff.

### CODE REVIEW

**Comment by Extravi** [comment]
your instance wont load https://i.ibb.co/XDD8pD1/image.png

**Comment by amogusussy** [comment]
> your instance wont load https://i.ibb.co/XDD8pD1/image.png

[It works fine on my computer.](https://imgur.com/gFmVJl6)

Maybe try reloading it?

**Comment by Extravi** [comment]
still not working https://i.ibb.co/1dbQjjv/image.png

**Comment by Extravi** [comment]
if you need help with it DM me on discord cta#3277

**Pull request closed without merging**
