### PR TITLE
Better image formatting

### PR DESCRIPTION
**Pull request by amogusussy**
This is it before. The images don't line up, there's only three per line, and it's just generally inconsistent.

image

This is it after. It's got more images per line, better lined up, and looks a lot nicer.

image

### CODE REVIEW

**Comment by hnhx** [comment]
Uh, why is the min css significantly longer than before?
The min css move from me was kinda dumb honestly, especially now that I have to check prs.
I think it should be reverted, it only saves like 2 KBs anyway.

Could you please remove the min css file and in the header.php change back 
`<link rel="stylesheet" type="text/css" href="static/css/styles_min.css"/>` to `<link rel="stylesheet" type="text/css" href="static/css/styles.css"/>`? Thanks and sorry for the inconvenience.

**Comment by hnhx** [comment]
Great pr btw.

**Comment by amogusussy** [comment]
It copied itself twice over for some reason.

I've changed the headers.php file, but if for whatever reason you want to go back, I've change the styles_min.css so its only got one copy.

**Comment by hnhx** [comment]
Thanks!

**Pull request merged**
