### PR TITLE
Add librex.zzls.xyz

### PR DESCRIPTION
**Pull request by Fijxu**
that's it

### CODE REVIEW

**Comment by hnhx** [comment]
You can move up your instance in the list since you host both tor and i2p instances. You can put your instance under librex.sesu.cc.

**Comment by hnhx** [comment]
Also there is a whitespace between CL and the flag :x

**Comment by Fijxu** [comment]
Fixed, it would be great to add some "trust check" linking the nginx configs of the owner of the instance so people can actually trust that instance and see if is logging something, here is mine anyways

https://git.zzls.xyz/Fijxu/etc-configs/src/branch/selfhost/nginx/sites-available/librex.zzls.xyz.conf

**Comment by hnhx** [comment]
People can change their nginx config any minute so thats not really needed.

**Pull request merged**
