### PR TITLE
Add new instance

### PR DESCRIPTION
**Pull request by whoisYoges**
Add new instance: <https://librex.yogeshlamichhane.com.np/>
My code editor messed up the json file and I messed up the branch earlier. So, I closed #124 and I'm opening this.

### CODE REVIEW

**Comment by hnhx** [comment]
Hey! Could you fix the intend in the json file? Thanks for hosting LibreX btw!

**Comment by whoisYoges** [comment]
I apologize, but I believe the indentation in the JSON file is correct. The issue is that the URL for my domain is so long that it is being wrapped onto a new line. Please let me know if I am mistaken. Thank you.

**Comment by whoisYoges** [comment]
> Hey! Could you fix the intend in the json file? Thanks for hosting LibreX btw!

Its done (i  guess)

**Comment by hnhx** [comment]
Thanks!

**Pull request merged**
