### PR TITLE
resolves a number of bugs, both in docker and master branch

### PR DESCRIPTION
**Pull request by juniorbotelho**
This PR addresses several bugs in both the Docker and master branches. Some of the errors were described in issues #173, #182, #178 and #177 (maybe the last two issues need user review on their instance). In addition, I changed some CURL settings because I had difficulty identifying the problem. The issue was that it only accepted requests with the IPv4 protocol.

Obs: Invidious URL has been changed:

```
 - "invidious_instance_for_video_results" => "https://invidious.namazso.eu",
 + "invidious_instance_for_video_results" => "https://invidious.snopyta.org",
```

I apologize for the delay. I was swamped with work this week.

### CODE REVIEW

**Comment by hnhx** [comment]
Hey, thanks for the PR.

CURLOPT_ENCODING, isn't what you may think it is, its for data compression see: https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html setting it to an empty string means that it will use any type of compression method available.

Also please remove the .vscode from the gitignore, by that logic we should add all DEs and code editors there.

**Comment by juniorbotelho** [comment]
> Hey, thanks for the PR.
> 
> CURLOPT_ENCODING, isn't what you may think it is, its for data compression see: https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html setting it to an empty string means that it will use any type of compression method available.
> 
> Also please remove the .vscode from the gitignore, by that logic we should add all DEs and code editors there.

Wow, you're totally right! I'm such a PHP newbie that I totally misunderstood those properties. Thanks a bunch for setting me straight - I'll get that sorted out pronto!

**Comment by juniorbotelho** [comment]
Hey, have you checked out the Docker image stats? It's wild - it's already gotten almost 8K downloads! Can you believe that?
https://hub.docker.com/u/librex

There are already people using it as a basis for tutorials <3
https://mariushosting.com/how-to-install-librex-on-your-synology-nas/

**Comment by juniorbotelho** [comment]
Fixed 💯

**Comment by hnhx** [comment]
Thanks!

Could you remove the .vscode thing btw? xp

**Comment by hnhx** [comment]
> Hey, have you checked out the Docker image stats? It's wild - it's already gotten almost 8K downloads! Can you believe that? https://hub.docker.com/u/librex
> 
> There are already people using it as a basis for tutorials <3 https://mariushosting.com/how-to-install-librex-on-your-synology-nas/

wow nice

**Pull request merged**
