### PR TITLE
Fixed drag and drop

### PR DESCRIPTION
**Pull request by pablouser1**
This pull request changes the following:
* Adds autocompletion following the OpenSearch standard
* Fixes the "drag and drop" search, this is done by changing the request from POST to GET. More info on the videos below

If you need something to be changed/explained please let me know.

https://user-images.githubusercontent.com/17802865/189452257-62fcae9b-3057-41fd-a83d-11df81b00725.mp4

https://user-images.githubusercontent.com/17802865/189452480-aaf90558-4055-45e1-b6fa-01e893c970c8.mp4

### CODE REVIEW

**Review by Extravi — APPROVED** [review]
this is very useful but i am not sure if the owner would approve this because everything you type is being sent to google in the search

**Review by hnhx — CHANGES_REQUESTED** [review]
Hey!

I don't want search suggestions in LibreX since if LibreX is set as the default search engine, anything that goes into the search bar from the user gets sent to the librex instance and to google which is horrible from a privacy point so please remove that.

As for the drag and drop search, sure, you can change the opensearch file from POST to GET, I will merge this once the suggestions are removed.

**Comment by Extravi** [comment]
Perhaps autocomplete should be turned off by default but can be enabled in settings.

**Comment by Extravi** [comment]
Why can't we add it the user can just disable it in settings https://i.ibb.co/YdY4N2r/Screenshot-20220917-181928.png 

If they wanted to disable it they can do it in settings.

**Comment by pablouser1** [comment]
> Why can't we add it the user can just disable it in settings https://i.ibb.co/YdY4N2r/Screenshot-20220917-181928.png
> 
> If they wanted to disable it they can do it in settings.

We can just do this and warn users about it if @hnhx is OK with it. If not, I'll just add the drag and drop fix and remove the autocomplete part.

**Comment by Extravi** [comment]
they aren't okay with it I asked them

**Comment by Extravi** [comment]
you am sure you have to remove autocomplete

**Comment by pablouser1** [comment]
Ok, I've removed the autocomplete part now.

**Review by Extravi — APPROVED** [review]
alright it should be fine now

**Comment by Extravi** [comment]
@hnhx

**Pull request merged**
