### PR TITLE
Added Frontends: Medium,GitHub and more

### PR DESCRIPTION
**Pull request by OshekharO**
Imgur,yt music,odysee, pastebin, reuters

### CODE REVIEW

**Comment by OshekharO** [comment]
Ready to be merged.

**Comment by OshekharO** [comment]
@hnhx now good?

**Comment by hnhx** [comment]
I have seen you linked the main instance of the project rather than the instances list. If a list of instances is not available then you shouldn't add a frontend since its just as centralized as the main product its proxying to the user.

**Comment by OshekharO** [comment]
> I have seen you linked the main instance of the projects in some cases rather than the instances list. If a list of instances is not available then you shouldn't add a frontend since its just as centralized as the main product its proxying to the user.

Now ok?

**Comment by hnhx** [comment]
Could you remove hyperpipe? It doesn't work without JS...
After that your PR will be ready to be merged.

**Comment by OshekharO** [comment]
> Could you remove hyperpipe? It doesn't work without JS... After that your PR will be ready to be merged.

Done

**Pull request merged**
