### PR TITLE
Fix search error when querying non-English keyword

### PR DESCRIPTION
**Pull request by gnh1201**
I tried to apply the same change to other torrent engines, but the merge fails.

### CODE REVIEW

**Review by Extravi — APPROVED** [review]

**Review by Extravi — CHANGES_REQUESTED** [review]
does not work for me? https://i.ibb.co/W0MkgrX/image.png

**Comment by Extravi** [comment]
i did not mean to approve

**Comment by gnh1201** [comment]
I'll look into what the problem is. I will leave a comment when it is revised.

**Comment by gnh1201** [comment]
I checked and found that there was a problem with the results of apibay.org. When querying non-English keywords, it seems to show random results.

image

Perhaps a separate idea is needed to solve this problem.

This issue will be closed soon. Thank you.

**Comment by Extravi** [comment]
okay

**Pull request closed without merging**
